# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app
    environment:
      - PYTHONUNBUFFERED=1
      - POSTGRES_URL
      - REDIS_HOST
      - REDIS_PORT
      - REDIS_USERNAME
      - REDIS_PASSWORD
      - GOOGLE_APP_PASSWORD
      - SMTP_HOST
      - SMTP_PORT
      - SMTP_USERNAME
      - SENDER_EMAIL
      - SENDER_NAME
      - ENV
      - GOOGLE_CLIENT_ID
      - GOOGLE_CLIENT_SECRET
      - GOOGLE_REDIRECT_URI
      - FRONTEND_URL
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
      - BACKEND_URL
    depends_on:
      - backend
